import type { ComponentProps } from 'react'
import {
  Activity,
  Bell,
  BriefcaseBusiness,
  ChevronRight,
  Circle,
  Code2,
  Contact,
  Cpu,
  Database,
  Download,
  ExternalLink,
  FileArchive,
  FileText,
  FolderKanban,
  FolderOpen,
  Gamepad2,
  GitBranch,
  Home,
  Image,
  Mail,
  Maximize2,
  MessageCircle,
  Minimize2,
  Minus,
  Monitor,
  MousePointerClick,
  PanelBottom,
  Power,
  RefreshCw,
  RotateCw,
  School,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  SquareTerminal,
  Trash2,
  Trophy,
  UserRound,
  Wifi,
  X,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const iconMap = {
  Activity,
  Bell,
  BriefcaseBusiness,
  ChevronRight,
  Circle,
  Code2,
  Contact,
  Cpu,
  Database,
  Download,
  ExternalLink,
  FileArchive,
  FileText,
  FolderKanban,
  FolderOpen,
  Gamepad2,
  Github: GitBranch,
  Home,
  Image,
  Linkedin: Contact,
  Mail,
  Maximize2,
  MessageCircle,
  Minimize2,
  Minus,
  Monitor,
  MousePointerClick,
  PanelBottom,
  Power,
  RefreshCw,
  RotateCw,
  School,
  Search,
  Send,
  Server,
  Settings,
  ShieldCheck,
  SquareTerminal,
  TerminalSquare: SquareTerminal,
  Trash2,
  Trophy,
  UserRound,
  Wifi,
  X,
} satisfies Record<string, LucideIcon>

interface IconProps extends Omit<ComponentProps<LucideIcon>, 'ref'> {
  name: string
}

export function Icon({ name, ...props }: IconProps) {
  const Lucide = iconMap[name] ?? Circle
  return <Lucide {...props} />
}
